export const GET_EXCHANGES_RELATION_INIT = "GET_EXCHANGES_RELATION_INIT";
export const GET_EXCHANGES_RELATION_SUCCESS = "GET_EXCHANGES_RELATION_SUCCESS";

export const UPLOAD_CONCILIATION = {
  INIT: "exchange/UPLOAD_CONCILIATION_INIT",
  SUCCESS: "exchange/UPLOAD_CONCILIATION_SUCCESS",
};

export const DOWNLOAD_CONCILIATION = {
  INIT: "exchange/DOWNLOAD_CONCILIATION_INIT",
  SUCCESS: "exchange/DOWNLOAD_CONCILIATION_SUCCESS",
};

export const GET_EXCHANGE_DETAILS = "GET_EXCHANGE_DETAILS";
export const GET_EXCHANGE_DETAILS_SUCCESS = "GET_EXCHANGE_DETAILS_SUCCESS";

export const CREATE_INVOICE = "CREATE_INVOICE";
export const CREATE_INVOICE_SUCCESS = "CREATE_INVOICE_SUCCESS";

export const CHANGE_ORDER_STATUS_INIT = "CHANGE_ORDER_STATUS_INIT";
export const CHANGE_ORDER_STATUS_SUCCESS = "CHANGE_ORDER_STATUS_SUCCESS";

export const CHANGE_STATUS = {
  INIT: "exchange/CHANGE_STATUS_INIT",
  SUCCESS: "exchange/CHANGE_STATUS_SUCCESS",
  CANCELLED: "exchange/CHANGE_STATUS_CANCELLED",
};

export const PROCESS_ORDER = {
  INIT: "exchange/PROCESS_ORDER_INIT",
  SUCCESS: "exchange/PROCESS_ORDER_SUCCESS",
};

export const REASSIGN_ORDER_INIT = "REASSIGN_ORDER_INIT";
export const REASSIGN_ORDER_SUCCESS = "REASSIGN_ORDER_SUCCESS";

export const EDIT_EXCHANGE = "EDIT_EXCHANGE";
export const EDIT_EXCHANGE_SUCCESS = "EDIT_EXCHANGE_SUCCESS";

export const SET_REVISION_INIT = "SET_REVISION_INIT";
export const SET_REVISION_SUCCESS = "SET_REVISION_SUCCESS";

export const API_ERROR = "CURRENCY_EXCHANGE_ERROR";
