export const GET_EXCHANGES_RELATION_INIT = "GET_EXCHANGES_RELATION_INIT";
export const GET_EXCHANGES_RELATION_SUCCESS = "GET_EXCHANGES_RELATION_SUCCESS";

export const UPLOAD_CONCILIATION = {
  INIT: "exchange/UPLOAD_CONCILIATION_INIT",
  SUCCESS: "exchange/UPLOAD_CONCILIATION_SUCCESS",
};

export const DOWNLOAD_CONCILIATION = {
  INIT: "exchange/DOWNLOAD_CONCILIATION_INIT",
  SUCCESS: "exchange/DOWNLOAD_CONCILIATION_SUCCESS",
};

export const GET_EXCHANGE_DETAILS = "GET_EXCHANGE_DETAILS";
export const GET_EXCHANGE_DETAILS_SUCCESS = "GET_EXCHANGE_DETAILS_SUCCESS";

export const CREATE_INVOICE = "CREATE_INVOICE";
export const CREATE_INVOICE_SUCCESS = "CREATE_INVOICE_SUCCESS";

export const CHANGE_ORDER_STATUS_INIT = "CHANGE_ORDER_STATUS_INIT";
export const CHANGE_ORDER_STATUS_SUCCESS = "CHANGE_ORDER_STATUS_SUCCESS";

export const VALIDATE_EXCHANGE = "VALIDATE_EXCHANGE";
export const VALIDATE_EXCHANGE_SUCCESS = "VALIDATE_EXCHANGE_SUCCESS";

export const REASSIGN_ORDER_INIT = "REASSIGN_ORDER_INIT";
export const REASSIGN_ORDER_SUCCESS = "REASSIGN_ORDER_SUCCESS";

export const APPROVE_EXCHANGE = "APPROVE_EXCHANGE";
export const APPROVE_EXCHANGE_SUCCESS = "APPROVE_EXCHANGE_SUCCESS";
export const APPROVE_EXCHANGE_CANCELED = "APPROVE_EXCHANGE_CANCELED";

export const DECLINE_EXCHANGE = "DECLINE_EXCHANGE";
export const DECLINE_EXCHANGE_SUCCESS = "DECLINE_EXCHANGE_SUCCESS";
export const DECLINE_EXCHANGE_CANCELED = "DECLINE_EXCHANGE_CANCELED";

export const EDIT_EXCHANGE = "EDIT_EXCHANGE";
export const EDIT_EXCHANGE_SUCCESS = "EDIT_EXCHANGE_SUCCESS";

export const SET_REVISION_INIT = "SET_REVISION_INIT";
export const SET_REVISION_SUCCESS = "SET_REVISION_SUCCESS";

export const API_ERROR = "CURRENCY_EXCHANGE_ERROR";
