export const GET_WITHDRAWS_INIT = 'GET_WITHDRAWS_INIT';
export const GET_WITHDRAWS_SUCCESS = 'GET_WITHDRAWS_SUCCESS';

export const GET_WITHDRAW_DETAILS_INIT = 'GET_WITHDRAW_DETAILS_INIT';
export const GET_WITHDRAW_DETAILS_SUCCESS = 'GET_WITHDRAW_DETAILS_SUCCESS';

export const CHANGE_WITHDRAW_STATUS_INIT = 'CHANGE_WITHDRAW_STATUS_INIT';
export const CHANGE_WITHDRAW_STATUS_SUCCESS = 'CHANGE_WITHDRAW_STATUS_SUCCESS';

export const WITHDRAWS_ERROR = 'WITHDRAWS_ERROR';
