export const GET_FOREX_INIT = "GET_FOREX_INIT";
export const GET_FOREX_SUCCESS = "GET_FOREX_SUCCESS";

export const GET_ALL_RATES_INIT = "GET_ALL_RATES_INIT";
export const GET_ALL_RATES_SUCCESS = "GET_ALL_RATES_SUCCESS";

export const GET_RATES_INIT = "GET_RATES_INIT";
export const GET_RATES_SUCCESS = "GET_RATES_SUCCESS";

export const ADD_CURRENCY_PRICE_INIT = "ADD_CURRENCY_PRICE_INIT";
export const ADD_CURRENCY_PRICE_SUCCESS = "ADD_CURRENCY_PRICE_SUCCESS";

export const CLEAR_ALERT = "CLEAR_ALERT";

export const API_ERROR = "CURRENCY_PRICES_API_ERROR";
