export const GET_CB_ACCOUNTS = "GET_CB_ACCOUNTS";
export const GET_CB_ACCOUNTS_SUCCESS = "GET_CB_ACCOUNTS_SUCCESS";

export const ADD_CB_ACCOUNT = "ADD_CB_ACCOUNT";
export const ADD_CB_ACCOUNT_SUCCESS = "ADD_CB_ACCOUNT_SUCCESS";

export const EDIT_CB_ACCOUNT = "EDIT_CB_ACCOUNT";
export const EDIT_CB_ACCOUNT_SUCCESS = "EDIT_CB_ACCOUNT_SUCCESS";

export const EDIT_CB_BALANCE = "EDIT_CB_BALANCE";
export const EDIT_CB_BALANCE_SUCCESS = "EDIT_CB_BALANCE_SUCCESS";

export const API_ERROR = "CB_ACCOUNTS_ERROR";
