export const CREATE_BANK_ORDER_INIT = "CREATE_BANK_ORDER_INIT";
export const CREATE_BANK_ORDER_SUCCESS = "CREATE_BANK_ORDER_SUCCESS";

export const GET_BANK_ORDER_DETAILS_INIT = "GET_BANK_ORDER_DETAILS_INIT";
export const GET_BANK_ORDER_DETAILS_SUCCESS = "GET_BANK_ORDER_DETAILS_SUCCESS";

export const CHANGE_BANK_ORDER_STATUS_INIT = "CHANGE_BANK_ORDER_STATUS_INIT";
export const CHANGE_BANK_ORDER_STATUS_SUCCESS = "CHANGE_BANK_ORDER_STATUS_SUCCESS";

export const API_ERROR = "BANK_ORDER_ERROR";
