export const GET_ADMINS = {
  INIT: "admin/GET_ADMINS_INIT",
  SUCCESS: "admin/GET_ADMINS_SUCCESS",
  ERROR: "admin/GET_ADMINS_ERROR",
};

export const GET_OPERATORS = {
  INIT: "admin/GET_OPERATORS_INIT",
  SUCCESS: "admin/GET_OPERATORS_SUCCESS",
  ERROR: "admin/GET_OPERATORS_ERROR",
};

export const SET_ONLINE = {
  INIT: "admin/SET_ONLINE_INIT",
  SUCCESS: "admin/SET_ONLINE_SUCCESS",
  ERROR: "admin/SET_ONLINE_ERROR",
};

export const GET_OPENED_STATUS = {
  INIT: "admin/GET_OPENED_STATUS_INIT",
  SUCCESS: "admin/GET_OPENED_STATUS_SUCCESS",
  ERROR: "admin/GET_OPENED_STATUS_ERROR",
};

export const UPDATE_OPENED_STATUS = {
  INIT: "admin/UPDATE_OPENED_STATUS_INIT",
  SUCCESS: "admin/UPDATE_OPENED_STATUS_SUCCESS",
  ERROR: "admin/UPDATE_OPENED_STATUS_ERROR",
};
