import type { Metadata } from "next";
import { poppins, urbanist } from "@/utils/fonts";
import "@/styles/globals.css";
import { ThemeProvider } from "@/components/providers/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body
        className={`min-h-screen bg-background font-sans antialiased
        ${poppins.variable} ${urbanist.variable}
      `}
      >
        <ThemeProvider attribute='class' defaultTheme='dark' enableSystem disableTransitionOnChange>
          <main className='min-h-screen'>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
