export const GET_COUPONS_INIT = 'GET_COUPONS_INIT';
export const GET_COUPONS_SUCCESS = 'GET_COUPONS_SUCCESS';

export const GET_COUPONS_DETAILS_INIT = 'GET_COUPONS_DETAILS_INIT';
export const GET_COUPONS_DETAILS_SUCCESS = 'GET_COUPONS_DETAILS_SUCCESS';

export const DISABLE_COUPON_INIT = 'DISABLE_COUPON_INIT';
export const DISABLE_COUPON_SUCCESS = 'DISABLE_COUPON_SUCCESS';

export const ADD_COUPON_INIT = 'ADD_COUPON_INIT';
export const ADD_COUPON_SUCCESS = 'ADD_COUPON_SUCCESS';

export const EDIT_COUPON_INIT = 'EDIT_COUPON_INIT';
export const EDIT_COUPON_SUCCESS = 'EDIT_COUPON_SUCCESS';

export const DELETE_COUPON_INIT = 'DELETE_COUPON_INIT';
export const DELETE_COUPON_SUCCESS = 'DELETE_COUPON_SUCCESS';

export const COUPONS_ERROR = 'COUPONS_ERROR';
