export const GET_CLIENT_DETAILS = "GET_CLIENT_DETAILS";
export const GET_CLIENT_DETAILS_SUCCESS = "GET_CLIENT_DETAILS_SUCCESS";

export const GET_CLIENT_EXCHANGES = "GET_CLIENT_EXCHANGES";
export const GET_CLIENT_EXCHANGES_SUCCESS = "GET_CLIENT_EXCHANGES_SUCCESS";

export const GET_CLIENT_ACCOUNTS = "GET_CLIENT_ACCOUNTS";
export const GET_CLIENT_ACCOUNTS_SUCCESS = "GET_CLIENT_ACCOUNTS_SUCCESS";

export const ADD_PROFILE_INIT = "ADD_PROFILE_INIT";
export const ADD_PROFILE_SUCCESS = "ADD_PROFILE_SUCCESS";

export const EDIT_PROFILE_INIT = "EDIT_PROFILE_INIT";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";

export const UPLOAD_DOCUMENT_INIT = "UPLOAD_DOCUMENT_INIT";
export const UPLOAD_DOCUMENT_SUCCESS = "UPLOAD_DOCUMENT_SUCCESS";

export const EDIT_INFO_INIT = "EDIT_INFO_INIT";
export const EDIT_INFO_SUCCESS = "EDIT_INFO_SUCCESS";

export const DOWNLOAD_CLIENTS_INIT = "DOWNLOAD_CLIENTS_INIT";
export const DOWNLOAD_CLIENTS_SUCCESS = "DOWNLOAD_CLIENTS_SUCCESS";

export const EDIT_INTERPLAZA_INIT = "EDIT_INTERPLAZA_INIT";
export const EDIT_INTERPLAZA_SUCCESS = "EDIT_INTERPLAZA_SUCCESS";

export const DISABLE_CLIENT_INIT = "DISABLE_CLIENT_INIT";
export const DISABLE_CLIENT_SUCCESS = "DISABLE_CLIENT_SUCCESS";

export const DELETE_PROFILE_INIT = "DELETE_PROFILE_INIT";
export const DELETE_PROFILE_SUCCESS = "DELETE_PROFILE_SUCCESS";

export const API_ERROR = "CLIENTS_API_ERROR";
