export const GET_CLIENTS_INIT = 'GET_CLIENTS_INIT';
export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS';

export const GET_CLIENT_DETAILS = 'GET_CLIENT_DETAILS';
export const GET_CLIENT_DETAILS_SUCCESS = 'GET_CLIENT_DETAILS_SUCCESS';

export const GET_CLIENT_EXCHANGES = 'GET_CLIENT_EXCHANGES';
export const GET_CLIENT_EXCHANGES_SUCCESS = 'GET_CLIENT_EXCHANGES_SUCCESS';

export const GET_CLIENT_ACCOUNTS = 'GET_CLIENT_ACCOUNTS';
export const GET_CLIENT_ACCOUNTS_SUCCESS = 'GET_CLIENT_ACCOUNTS_SUCCESS';

export const EDIT_PROFILE_INIT = 'EDIT_PROFILE_INIT';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';

export const DOWNLOAD_CLIENTS_INIT = 'DOWNLOAD_CLIENTS_INIT';
export const DOWNLOAD_CLIENTS_SUCCESS = 'DOWNLOAD_CLIENTS_SUCCESS';

export const CLEAR_ALERT = 'CLIENTS_CLEAR_ALERT';
export const API_ERROR = 'CLIENTS_API_ERROR';
