name: developCI

on:
  push:
    branches:
      - "develop"
      - "fixes/*"
      - "features/*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_DEV_API_URL: ${{ secrets.DEV_API_URL }}
      REACT_APP_TEST_SOCKET_CONN: wss://socket-manager-ms-swe5i.ondigitalocean.app/ws
      AWS_CF_DISTRIBUTION_ID: E216R31QM6ITZB
      AWS_REGION: us-east-2
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Build de application
        run: yarn build:test
      - uses: jakejarvis/s3-sync-action@master
        name: Upload the app to S3 bucket
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.DEV_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}
          SOURCE_DIR: "build"
      - name: Create Cloudfront cache invalidation
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ env.AWS_CF_DISTRIBUTION_ID }}
          PATHS: "/*"
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
